---
title: 'Define “define"'
author: "Mara Averick"
date: '`r Sys.Date()`'
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* **_definiendum_**: the symbol, term, or phrase being defined  
* **_definiens_**: the symbol or group of symbols explaining the meaning of the _definiendum_  
* **_name_**: (J.S. Mill edition) only syntactic contribution of a name is its _referent_[^Mill1882]; cites Hobbes' definition that "a word taken at pleasure to serve for a mark which may raise in our mind a thought like to some thought we had before, and which being pronounced to others, may be to them a sign of what thought the speaker had before in his mind" (where _denotation_ = reference, and _connotation_ = meaning)
  - **_Syncategorematic terms_**: "Words which are not capable of being used as names, but only as parts of names" (p.53).  
  - **_Categorematic terms_**: "word[s] which could be used either as the subject or predicate of a proposition without being accompanied by any other word" (p.53).

## Lexical definitions

### Connotative meaning

### Denotative meaning

## Extensional vs intensional definitions

### Intensional definition

Gives the properties/conditions necessary (and sufficient) for something to be a referent to the term being defined.

### Extensional definition

A type of enumerative definition; lists all the members of the class of the term being defined.

## Non-lexical definition typology

### Stipulative

### Précising

### Theoretical

### Emotive

[^Mill1882]: Mill, John Stuart. 1882. A System of Logic, Ratiocinative and Inductive. Eighth. New York: Harper & Brothers. 
